name: Deployment

concurrency: 
  group: production
  cancel-in-progress: true

on:
  release:
    types: [published]

jobs:
  staging:
    name: Staging Deploy
    runs-on: ubuntu-latest
    environment: STAGING
    steps:
      - name: deploy
        run: |
          echo "Deploy Staging!";

  production:
    name: Production Deploy
    runs-on: ubuntu-latest
    environment: 
      name: PRODUCTION
      url: https://eduardoborges.dev
    steps:
      - name: deploy
        run: |
          echo "Deploy Staging!"

          