name: CD
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: NPM Cache
        uses: c-hive/gha-npm-cache@v1

      - name: Install dependencies
        run: npm ci

      - name: Publish Release
        run: npx semantic-release --ci
